apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJVR2x6YTJ4dmRrTnZjanBuYUhCZmIydHJURXRFVTJKNWVrMXdha0ZxVTBoNFVtaERXSE0wTUU1cGN6bDRNbmhXU0d3MCIKICAgICAgICB9CiAgICB9LAogICAgImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCiAgICAiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCiAgICAicGx1Z2lucyI6IHsKICAgICAgICAiZGVidWciOiB7CiAgICAgICAgICAgICJob29rcyI6ICJleGVjIgogICAgICAgIH0sCiAgICAgICAgInNjb3V0IjogewogICAgICAgICAgICAiaG9va3MiOiAicHVsbCxidWlsZHggYnVpbGQiCiAgICAgICAgfQogICAgfSwKICAgICJmZWF0dXJlcyI6IHsKICAgICAgICAiaG9va3MiOiAidHJ1ZSIKICAgIH0KfQ==
type: kubernetes.io/dockerconfigjson
