{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: proxy-service
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: proxy-service
          image: {{ .Values.proxyService.image.repository }}:{{ .Values.proxyService.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.proxyService.service.targetPort }}
          env:
            - name: PORT
              value: {{ .Values.proxyService.service.targetPort | quote }}
            - name: MONOLITH_URL
              valueFrom:
                configMapKeyRef:
                  name: cinemaabyss-config
                  key: MONOLITH_URL
            - name: MOVIES_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: cinemaabyss-config
                  key: MOVIES_SERVICE_URL
            - name: EVENTS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: cinemaabyss-config
                  key: EVENTS_SERVICE_URL
            - name: GRADUAL_MIGRATION
              valueFrom:
                configMapKeyRef:
                  name: cinemaabyss-config
                  key: GRADUAL_MIGRATION
            - name: MOVIES_MIGRATION_PERCENT
              valueFrom:
                configMapKeyRef:
                  name: cinemaabyss-config
                  key: MOVIES_MIGRATION_PERCENT
          envFrom:
            - configMapRef:
                name: cinemaabyss-config
            - secretRef:
                name: cinemaabyss-secrets
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: proxy-service
  ports:
  - port: {{ .Values.proxyService.service.port }}
    targetPort: {{ .Values.proxyService.service.targetPort }}
  type: {{ .Values.proxyService.service.type }}
{{- end }}